### ISSUE TITLE
Run tests automatically every day?

### ISSUE THREAD

**Issue by claudiofullscreen** [Fullscreen/funky#40]
Can we find a third-party service that runs the test suite every day and sends us an email if it's broken?

In this way we can be notified if Facebook changes their API or HTML structure.

**Comment by jwworth** [comment]
Looks like your CI tool, TravisCI, supports this: https://docs.travis-ci.com/user/cron-jobs/
It would have to be set up by somebody with access to the repository and build console.

**Comment by claudiofullscreen** [comment]
@jwworth Thank you so much for the tip and for stopping by!

I didn't know about Travis Cron Jobs. Will look into them now. 🎀

**Comment by claudiofullscreen** [comment]
Travis Cron Jobs are running!! Thanks @jwworth
